print("Enter First Number")
No1 = input()
print("Enter Second Number")
No2 = input()
print(type(No1))
print(type(No2))
sum = int(No1) + int(No2)
print(type(No1))
print(type(No2))
print("Sum Of number is :",sum)